apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0dHJlbmQxLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJkWE5sY21OeVpXUTZTbVp5YjJkQU1USXoiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
